eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka2
  #    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.3.6:${server.port}/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false

zipkin:
  host: 192.168.3.6

spring:
  zipkin:
    service:
      name: ${spring.application.name}
    sender:
      type: web
    base-url: http://${zipkin.host:127.0.0.1}:${zipkin.port:9411}
  sleuth:
    sampler:
      probability: 1.0
