test:
  configCenter:
    key1: "configCenter valid"

spring:
  cloud:
    stream:
      bindings:
        testStreamOutput:
          destination: testStream
        testStreamInput:
          destination: testStream
          group: testStream-group
